- name: "Create inventory and configure source in AWX"
  block:
    - name: "Create inventory in AWX"
      awx.awx.inventory:
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        organization: "{{ item.organization }}"
        state: present
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ inventories }}"

    - name: "Remove lock files and project cache"
      block:
        - name: "Find project directory by project name"
          find:
            paths: "{{ persistent_container_storage_dir }}/awx/projects/"
            patterns: "_*_{{ item.source_project | lower | replace(' ', '_') }}*"
            file_type: directory
          register: project_dirs
          loop: "{{ inventories }}"
          when: item.source_project is defined and item.sync_on_create | default(false)

        - name: "Remove project cache directories"
          file:
            path: "{{ item.files[0].path }}"
            state: absent
          loop: "{{ project_dirs.results }}"
          when: item.files | length > 0

        - name: "Remove lock files associated with project"
          file:
            path: "{{ item.files[0].path }}.lock"
            state: absent
          loop: "{{ project_dirs.results }}"
          when: item.files | length > 0
      ignore_errors: true

    - name: "Sync project before syncing inventory source"
      awx.awx.project_update:
        name: "{{ item.source_project }}"
        wait: true
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ inventories }}"
      when: item.source_project is defined and item.sync_on_create | default(false)

    - name: "Configure inventory source"
      awx.awx.inventory_source:
        name: "{{ item.inventory_source_name }}"
        inventory: "{{ item.name }}"
        source: "scm"
        source_project: "{{ item.source_project }}"
        source_path: "{{ item.source_path }}"
        credential: "{{ item.credential | default(omit) }}"
        overwrite: "{{ item.overwrite }}"
        update_on_launch: "{{ item.update_on_launch }}"
        update_cache_timeout: "{{ item.update_cache_timeout | default(omit) }}"
        state: present
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ inventories }}"
      when: item.inventory_source_name is defined and item.inventory_source_name != ""

    - name: "Sync inventory source if configured"
      awx.awx.inventory_source_update:
        name: "{{ item.inventory_source_name }}"
        inventory: "{{ item.name }}"
        wait: true
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ inventories }}"
      when: item.sync_on_create | default(false)

    - name: "Add hosts to inventory"
      awx.awx.host:
        name: "{{ item.name }}"
        inventory: "{{ item.inventory }}"
        variables: "{{ item.vars | default(omit) }}"
        state: present
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ hosts }}"

    - name: "Print success message for each inventory"
      debug:
        msg: "Configured inventory {{ item.name }} successfully."
      loop: "{{ inventories }}"

  rescue:
    - name: "Handle failure during project configuration"
      debug:
        msg: "Failed to configure inventory {{ item.name }}."
      loop: "{{ inventories }}"
      loop_control:
        loop_var: "item"

  when: set_inventories is defined and set_inventories | bool
