---
- name: "Loop over projects and configure them in AWX"
  block:
    - name: "Configure project in AWX"
      awx.awx.project:
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        organization: "{{ item.organization }}"
        scm_type: "{{ item.scm_type | default(omit) }}"
        scm_url: "{{ item.scm_url | default(omit) }}"
        scm_branch: "{{ item.scm_branch | default(omit) }}"
        scm_update_on_launch: "{{ item.scm_update_on_launch | default(omit) }}"
        local_path: "{{ item.local_path | default(omit) }}"
        state: present
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ projects }}"
      failed_when: "'local_path' in ansible_facts and 'already being used' not in ansible_facts.msg"

    - name: "Print success message for each project"
      debug:
        msg: "Configured project {{ item.name }} successfully."
      loop: "{{ projects }}"

  rescue:
    - name: "Handle failure during project configuration"
      debug:
        msg: "Failed to configure project {{ item.name }}."
      loop: "{{ projects }}"

  when: set_projects is defined and set_projects | bool