---
- name: Request Personal Tower CLI Token via AWX API
  ansible.builtin.uri:
    url: "http://{{ awx_admin_user }}:{{ awx_admin_password }}@{{ awx_base_url }}/api/v2/users/1/personal_tokens/"
    method: POST
    headers:
      Content-Type: "application/json"
    body: '{"description":"Personal Tower CLI token", "application":null, "scope":"write"}'
    body_format: json
    return_content: true
    validate_certs: false
  register: awx_token_response

- name: Parse the token from the AWX API response
  ansible.builtin.set_fact:
    awx_api_token: "{{ awx_token_response.json.token }}"

- name: Show the retrieved API token
  ansible.builtin.debug:
    msg: "The retrieved AWX API token is: {{ awx_api_token }}"
...
