---
- name: "Loop over credentials and configure them in AWX"
  block:
    - name: "Configure credential in AWX"
      awx.awx.credential:
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        organization: "{{ item.organization }}"
        credential_type: "{{ item.credential_type }}"
        inputs: "{{ item.inputs | default(omit) }}"
        state: present
        controller_host: "{{ awx_base_url }}"
        controller_username: "{{ awx_admin_user }}"
        controller_password: "{{ awx_admin_password }}"
        validate_certs: false
      loop: "{{ credentials }}"
      failed_when: "'already exists' not in ansible_facts.msg"

    - name: "Print success message for each credential"
      debug:
        msg: "Configured credential {{ item.name }} successfully."
      loop: "{{ credentials }}"

  rescue:
    - name: "Handle failure during credential configuration"
      debug:
        msg: "Failed to configure credential {{ item.name }}."
      loop: "{{ credentials }}"

  when: set_credentials is defined and set_credentials | bool
...
