---
- name: Get list of AWX pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ awx_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=awx-task"
  register: awx_pods

- name: Collect pod name
  ansible.builtin.set_fact:
    podname: "{{ item.metadata.name }}"
  loop: "{{ awx_pods.resources }}"

- name: Get list of AWX pod postgres
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ awx_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=postgres-15"
  register: awx_pods2

- name: Collect pod postgres name
  ansible.builtin.set_fact:
    podname_postgres: "{{ item.metadata.name }}"
  loop: "{{ awx_pods2.resources }}"

- name: Tar project data in the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname }}"
    container: "awx-task"
    command: "tar czf /tmp/projects_backup.tar.gz -C /var/lib/awx/projects ."

- name: Copy projects backup to local machine
  command: >
    kubectl cp {{ awx_namespace }}/{{ podname }}:/tmp/projects_backup.tar.gz {{ persistent_container_storage_dir }}/awx/projects_backup.tar.gz

- name: Extract projects backup to PV
  ansible.builtin.shell: |
    tar xzf {{ persistent_container_storage_dir }}/awx/projects_backup.tar.gz -C {{ persistent_container_storage_dir }}/awx/projects

- name: Create backup directory in the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "mkdir -p /tmp/awx_backup"

- name: Backup entire AWX database
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: >
      pg_dump -U {{ awx_db_user }} -d {{ awx_db_name }} --exclude-table=public.main_job --exclude-table=public.main_unifiedjob --exclude-table=public.auth_user --exclude-table=public.auth_user_groups --exclude-table=public.auth_user_user_permissions --data-only -f /tmp/awx_backup/full_backup.sql

- name: Copy backup from the container to local machine
  command: >
    kubectl cp {{ awx_namespace }}/{{ podname_postgres }}:/tmp/awx_backup/full_backup.sql {{ bastion_install_dir }}/full_backup.sql
...
