---
- name: Wait 60 seconds for migration pods to spin up
  ansible.builtin.wait_for:
    timeout: 60

- name: Check if AWX is in migration state
  ansible.builtin.uri:
    url: "{{ awx_base_url }}/"
    method: GET
    return_content: yes
    follow_redirects: all
  register: page_content
  retries: 20
  delay: 30
  until: "'AWX Upgrading' not in page_content.content"

- name: Get list of AWX pod postgres
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ awx_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=postgres-15"
  register: awx_pods2

- name: Collect pod postgres name
  ansible.builtin.set_fact:
    podname_postgres: "{{ item.metadata.name }}"
  loop: "{{ awx_pods2.resources }}"

- name: Create backup directory in the container
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "mkdir -p /tmp/awx_backup"

- name: Copy backup archive from the container to local machine
  ansible.builtin.command: >
    kubectl cp {{ bastion_install_dir }}/full_backup.sql {{ awx_namespace }}/{{ podname_postgres }}:/tmp/awx_backup/full_backup.sql

- name: Drop all relevant tables before restore
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: >
      psql -U {{ awx_db_user }} -d {{ awx_db_name }} -c "
      DROP TABLE IF EXISTS 
      main_credentialtype, 
      main_rbac_roles, 
      main_credential, 
      main_organization, 
      main_inventory, 
      main_host, 
      main_executionenvironment, 
      main_schedule, 
      main_unifiedjobtemplate, 
      main_project, 
      main_projectupdate, 
      main_systemjobtemplate CASCADE;
      "

- name: Restore backup using psql
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U {{ awx_db_user }} -d {{ awx_db_name }} -f /tmp/awx_backup/full_backup.sql"
...
