---
- name: Get list of AWX pod postgres
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ awx_namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=postgres-15"
  register: awx_pods2

- name: Collect pod postgres name
  ansible.builtin.set_fact:
    podname_postgres: "{{ item.metadata.name }}"
  loop: "{{ awx_pods2.resources }}"

- name: Copy backup archive from the container to local machine
  ansible.builtin.command: >
    kubectl cp {{ bastion_install_dir }}/awx_backup.tar.gz {{ awx_namespace }}/{{ podname_postgres }}:/tmp/awx_backup.tar.gz

- name: Extract backup archive in the container
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "tar xzf /tmp/awx_backup.tar.gz -C /tmp/awx_backup"

- name: Restore credentials
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U awx -d awx -f /tmp/awx_backup/credentials.sql"

- name: Restore projects
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U awx -d awx -f /tmp/awx_backup/projects.sql"

- name: Restore job templates
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U awx -d awx -f /tmp/awx_backup/job_templates.sql"

- name: Restore execution environments
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U awx -d awx -f /tmp/awx_backup/execution_environments.sql"

- name: Restore inventories and hosts
  kubernetes.core.k8s_exec:
    namespace: "{{ awx_namespace }}"
    pod: "{{ podname_postgres }}"
    command: "psql -U awx -d awx -f /tmp/awx_backup/inventories_hosts.sql"
...
