---
- name: Install required packages on Ubuntu/Debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - make
    - docker
    - python3-pip

- name: Stop and disable UFW
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  ignore_errors: true
...
